source "https://rubygems.org"
ruby ">= 3.2.0"
gem "rails", "8.1.3.1"
gem "sqlite3", "~> 2.9"
gem "puma", "~> 7.0"
gem "minitest", "~> 5.25"
# Rails 8.1 JSON decoding uses the JSON 2.x positional options API.
gem "json", "~> 2.21"
